"""empty message

Revision ID: 0fc0fe86f566
Revises: 
Create Date: 2021-01-11 12:34:52.264997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fc0fe86f566'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('conversion_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=2), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('fullname', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=250), nullable=True),
    sa.Column('query', sa.String(length=250), nullable=True),
    sa.Column('product', sa.String(length=250), nullable=True),
    sa.Column('campaign', sa.String(length=250), nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id_snl', sa.String(length=24), nullable=True),
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rate_id'], ['rate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead')
    op.drop_table('request')
    op.drop_table('rate')
    # ### end Alembic commands ###
